### ISSUE TITLE
Create Smith-Waterman Function

### ISSUE THREAD

**Issue by tymaxjones** [tymaxjones/SequenceAlignment-#1]
develop smith waterman function:

- Should input 2 sequences, gap penalty, match score, mismatch scores
- output the score of their similarity
- Output the alignment of the two sequences:

Ex:

Sequence 1 
ACTGTCAT

Sequence 2
CTGACATG

Output:

score

alignment
ACTGTCAT.
.CTGACATG

**Comment by petriiick** [comment]
Hi, I just have a question about whether this prompt is right cuz I tried to search different versions of the Smith-waterman function, even with Chatgpt, I just can't get the function to fulfill this requirement.

**Comment by tymaxjones** [comment]
Hey, sorry my output alignment was just made up. 
Here's what I got when I ran it through the Smith-Waterman at [EMBOSS water](https://www.ebi.ac.uk/Tools/psa/emboss_water/)
```
########################################
# Program: water
# Rundate: Tue 18 Apr 2023 02:42:45
# Commandline: water
#    -auto
#    -stdout
#    -asequence emboss_water-I20230418-024150-0761-15078443-p1m.asequence
#    -bsequence emboss_water-I20230418-024150-0761-15078443-p1m.bsequence
#    -datafile EDNAFULL
#    -gapopen 10.0
#    -gapextend 0.5
#    -aformat3 pair
#    -snucleotide1
#    -snucleotide2
# Align_format: pair
# Report_file: stdout
########################################

#=======================================
#
# Aligned_sequences: 2
# 1: EMBOSS_001
# 2: EMBOSS_001
# Matrix: EDNAFULL
# Gap_penalty: 10.0
# Extend_penalty: 0.5
#
# Length: 7
# Identity:       6/7 (85.7%)
# Similarity:     6/7 (85.7%)
# Gaps:           0/7 ( 0.0%)
# Score: 26.0
# 
#
#=======================================

EMBOSS_001         2 CTGTCAT      8
                     |||.|||
EMBOSS_001         1 CTGACAT      7


#---------------------------------------
```
Here are a couple resources:
https://en.wikipedia.org/wiki/Smith%E2%80%93Waterman_algorithm
https://www.youtube.com/watch?v=F1YId_z4pc8
